In [4]:
# Read in dataset
import pandas as pd
apps_with_duplicates = pd.read_csv('E:\\github\DataScience-Projects\The Android App Market on Google Play\datasets\\apps.csv')

# Drop duplicates
apps = apps_with_duplicates.drop_duplicates(subset=['App'])

# Print the total number of apps
print('Total number of apps in the dataset = ',len(apps.App))

# Print a concise summary of apps dataframe
print(apps.info())

# Have a look at a random sample of n rows
n = 5
apps.sample(n)

Total number of apps in the dataset =  9659
<class 'pandas.core.frame.DataFrame'>
Int64Index: 9659 entries, 0 to 9658
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      9659 non-null   int64
 1   App             9659 non-null   object
 2   Category        9659 non-null   object
 3   Rating          8196 non-null   float64
 4   Reviews         9659 non-null   int64
 5   Size            8432 non-null   float64
 6   Installs        9659 non-null   object
 7   Type            9659 non-null   object
 8   Price           9659 non-null   object
 9   Content Rating  9659 non-null   object
 10  Genres          9659 non-null   object
 11  Last Updated    9659 non-null   object
 12  Current Ver     9651 non-null   object
 13  Android Ver     9657 non-null   object
dtypes: float64(2), int64(2), object(10)
memory usage: 1.1+ MB
None

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
6547,7603,Glitch Fixers: Powerpuff Girls,GAME,4.4,39698,51.0,"5,000,000+",Free,0,Everyone,Arcade,"December 1, 2016",1.0.0,4.1 and up
3640,4546,Learn R Programming,BOOKS_AND_REFERENCE,NaN,0,29.0,10+,Free,0,Everyone,Books & Reference,"April 28, 2018",1,4.1 and up
6336,7383,Thistletown CI,PRODUCTIVITY,1.0,1,6.6,100+,Free,0,Everyone,Productivity,"March 15, 2018",41.9,4.1 and up
2167,2761,Urban Outfitters,SHOPPING,4.2,4158,23.0,"500,000+",Free,0,Teen,Shopping,"July 2, 2018",2.8,4.0.3 and up
2313,2964,"theScore: Live Sports Scores, News, Stats & Vi...",SPORTS,4.4,133825,34.0,"10,000,000+",Free,0,Everyone 10+,Sports,"July 25, 2018",6.17.2,4.4 and up

In [5]:
# List of characters to remove
chars_to_remove = [',' ,'$' ,'+']
# List of column names to clean
cols_to_clean = ["Installs","Price"]

# Loop for each column
for col in cols_to_clean:
    # Replace each character with an empty string
    for char in chars_to_remove:
        apps[col] = apps[col].astype(str).str.replace(char, '')
    # Convert col to numeric
    apps[col] = pd.to_numeric(apps[col])

In [6]:
import plotly
plotly.offline.init_notebook_mode(connected=True)
import plotly.graph_objs as go

# Print the total number of unique categories
num_categories = len(apps["Category"].unique())
print('Number of categories = ', num_categories)

# Count the number of apps in each 'Category' and sort them in descending order
num_apps_in_category = apps["Category"].value_counts().sort_values(ascending = False)

data = [go.Bar(
        x = num_apps_in_category.index, # index = category name
        y = num_apps_in_category.values, # value = count
)]

plotly.offline.iplot(data)

ModuleNotFoundError: No module named 'plotly'

In [7]:

import plotly
plotly.offline.init_notebook_mode(connected=True)
import plotly.graph_objs as go

# Print the total number of unique categories
num_categories = len(apps['Category'].unique())
print('Number of categories = ', num_categories)

# Count the number of apps in each 'Category' and sort them in descending order
num_apps_in_category = apps['Category'].value_counts().sort_values(ascending = False)

data = [go.Bar(
        x = num_apps_in_category.index, # index = category name
        y = num_apps_in_category.values, # value = count
)]

plotly.offline.iplot(data)

ModuleNotFoundError: No module named 'plotly'